swiftgen:
	# Ref: https://github.com/SwiftGen/SwiftGenPlugin#using-it-as-a-command
	# When running this command, `swiftgen.yml` can't contain Environment Variables like ${TARGET_NAME}.
	swift package --allow-writing-to-package-directory generate-code-for-resources
